### ISSUE TITLE
This flow does not work in the new application schema with different app_id fields

### ISSUE THREAD

**Issue by stasbar** [mongodb-developer/SocialStats#25]
Hi, I really appreaciate what you have done, it saved me a lot of time. There is one problem though. It looks like mongo/realm changed the [application schema](https://docs.mongodb.com/realm/deploy/application-configuration-files/). The config `config.json` now require application-specific id `app_id` field, so this file can not be shared across different realm applications. When I try to deploy it to a different application I get 

> Failed: failed to import app: cannot change name of app from source control

 Did you solve this problem? Or do you have any idea how to solve it?

**Comment by stasbar** [comment]
Ok, nevermind. I just found the answer. I can remove the properties from `config.json` and it still works 😄

**Comment by ljhaywar** [comment]
Woot!  Glad you were able to get it working!

**Comment by stasbar** [comment]
Yeah, and btw. mongo/realm now supports deployment from specific branch, so there is no need to create multiple repos anymore :)

**Comment by ljhaywar** [comment]
Yes! 🎉

I updated my pipeline and the Readme about a month ago to use multiple branches instead of multiple repos. Much easier.
