### ISSUE TITLE
e2e tests for user/password auth

### ISSUE THREAD

**Issue by cesarvarela** [mongodb-developer/SocialStats#37]
Are there any examples on how to handle e2e tests for user/password authentication?

Should be something like this I think?

https://docs.cypress.io/guides/testing-strategies/auth0-authentication#Auth0-Application-Setup

**Comment by ljhaywar** [comment]
Hi @cesarvarela,
I'm not aware of any examples off the top of my head. This is a great question for the MongoDB Community: community.mongodb.com. MongoDB employees and members of our wider MongoDB community are there every day answering questions.
